### ISSUE TITLE
Are you using a older version of SFML ?

### ISSUE THREAD

**Issue by SohanChy** [abrarShariar/Star_Fighters#2]
I tried to pack a make a release build but it would not compile.
But after replacing your DLLs with the ones from SFML-2.3.2,
 they work fine now.

I have not uploaded the dlls or a compiled exe,
your older version should compile just fine as you have not used any unsupported functions.
This is just a suggestion, 
maybe you should switch to the latest version of sfml?

**Comment by abrarShariar** [comment]
Unfortunately I had used SFML -2.2 version. Will upgrade it to v.3 soon.
